services:
 transmission:
    image: linuxserver/transmission:4.0.5
    container_name: transmission
    restart: unless-stopped
    volumes:
      - ${TRANSMISSION_VOLUME_CONFIG}:/config
      - ${TRANSMISSION_VOLUME_DOWNLOADS}:/downloads
      - ${TRANSMISSION_VOLUME_WATCH}:/watch
    environment:
      - PUID=${TRANSMISSION_PUID}
      - PGID=${TRANSMISSION_PGID}
      - TZ=${TRANSMISSION_TZ}
      - USER=${TRANSMISSION_WEB_USER}
      - PASS=${TRANSMISSION_WEB_PASS}
    ports:
      - 51413:51413
      - 51413:51413/udp
      - 9091:9091
    networks:
      - proxy

networks:
  proxy:
    external: true