services:
  caddy:
    image: caddy:2
    container_name: caddy
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
      - 443:443/udp
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ${CADDY_VOLUME_DATA}:/data
      - ${CADDY_VOLUME_CONFIG}:/config
    networks:
      - proxy

networks:
  proxy:
    external: true
